const UserRole = {
  Contributor: "Contributor",
  OwnerCourse: "Owner course",
  OwnerTask: "Owner Task",
  MediaContent: "Media content",
  OwnerClass: "Owner Class",
  OwnerEvent: "Owner event",
  ViewAllTask: "View all task",
  ManagerTestCenter: "Manager Test center",
  OwnerTestCenter: "Owner test-center",
  ManagerFA: "Manager FA",
  OwnerWarehouse: "Owner warehouse",
  ManagerWarehouse: "Manager warehouse",
  Editor: "Editor",
  Moderator: "Moderator",
  Author: "Author",
  OwnerContest: "Owner Contest",
  ReviewTask: "Review Task",
  ReviewContest: "Review Contest",
  ReviewCourse: "Review Course",
  ReviewClass: "Review Class",
  ReviewEvent: "Review event",
  ReviewTestCenter: "Review Test center",
  TestCenter: "Test center",
  MonitorGame: "Monitor game",
  PublishTask: "Publish task",
  ManagerContent: "Manager Content",
  ReviewBlog: "Review blog",
  Blog: "Blog",
  ManagerBlog: "Manager blog",
  OwnerBlogPost: "Owner Blog Post",
  ReviewBlogPost: "Review Blog Post",
  ApproveBlogger: "Approve Blogger",
  Administrator: "Administrator",
  SiteOwner: "SiteOwner",
  ManageVoucher: "Manager Voucher",
  MonitorOrder: "Monitor Order",
};

export default UserRole;
