# Base Image
FROM node:20-alpine AS BASE
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile
RUN npm install --include=optional sharp
RUN npm install --os=linux --libc=musl --cpu=x64 sharp

# Build Image
FROM node:20-alpine AS BUILD
WORKDIR /app
COPY --from=BASE /app/node_modules ./node_modules
COPY . .
COPY .env.* ./
COPY .eslintrc.json ./
RUN yarn build

# Runner Image
FROM node:20-alpine AS RUNNER
WORKDIR /app
ENV NODE_ENV production

# Update the package list and install fontconfig
RUN apk add fontconfig

# Copy application files
COPY --from=BUILD /app ./

# Copy fonts to the container
COPY ./public/fonts/Plus_Jakarta_Sans /usr/share/fonts/ 

# Run fc-cache to build the font information cache files
RUN fc-cache -f -v

# Expose port 80
EXPOSE 80

# Define the command to run the application
CMD ["npm", "run", "start", "--", "--port", "80"]
