import { EvaluateGradeEnum, EvaluateStatusEnum } from "@src/constants/evaluate/evaluate.constant";

export const listSelect = [
  {
    label: "All",
    textColor: "",
    bgColor: "",
    status: EvaluateStatusEnum.None,
    grade: 7,
  },
  {
    label: "In Progress",
    textColor: "#2c31cf",
    bgColor: "rgba(0,82,204,.2)",
    status: EvaluateStatusEnum.Running,
    grade: 9,
  },
  {
    label: "Not yet started",
    textColor: "",
    bgColor: "#fec",
    status: EvaluateStatusEnum.Waiting,
    grade: 8,
  },
  {
    label: "Expired",
    textColor: "",
    bgColor: "#a5adba",
    status: EvaluateStatusEnum.Expired,
    grade: 11,
  },
  {
    label: "High distinction",
    textColor: "#fff",
    bgColor: "#ec467c",
    labelPoint: "900+",
    status: EvaluateStatusEnum.Finished,
    grade: EvaluateGradeEnum.HighDistinction,
  },
  {
    label: "Distinction",
    textColor: "#fff",
    bgColor: "#fe8900",
    labelPoint: "800-899",
    status: EvaluateStatusEnum.Finished,
    grade: EvaluateGradeEnum.Distinction,
  },
  {
    label: "Credit",
    textColor: "#fff",
    bgColor: "#6554c0",
    labelPoint: "650-799",
    status: EvaluateStatusEnum.Finished,
    grade: EvaluateGradeEnum.Credit,
  },
  {
    label: "Pass",
    textColor: "#fff",
    bgColor: "#00a9de",
    labelPoint: "450-649",
    status: EvaluateStatusEnum.Finished,
    grade: EvaluateGradeEnum.Pass,
  },
  {
    label: "Weak",
    textColor: "#fff",
    bgColor: "#36b37e",
    labelPoint: "300-449",
    status: EvaluateStatusEnum.Finished,
    grade: EvaluateGradeEnum.Weak,
  },
  {
    label: "Poor",
    textColor: "",
    bgColor: "#dcdff1",
    labelPoint: "0-299",
    status: EvaluateStatusEnum.Finished,
    grade: EvaluateGradeEnum.Poor,
  },
];
