export const LEARN_API = process.env.NEXT_PUBLIC_API_LEARN;
export const FRIEND_API = process.env.NEXT_PUBLIC_API_FRIEND;

export enum FORM_ACTION_CONSTANT {
  DEFAULT_CREATE_PARAM = "create",
}

export enum LOCAL_STORAGE {
  TOKEN = "ACCESS_TOKEN",
}
export enum PubsubTopic {
  ACTIVITY_CHANGED = "ACTIVITY_CHANGED",
  OPEN_CONFIRMATION_MODAL = "OPEN_CONFIRMATION_MODAL",
  NOTIFICATION = "NOTIFICATION",
  API_ERROR = "API_HTTP_STATUS_NOT_SUCCESS",
  QUESTIONBANK_CHANGED = "QUESTIONBANK_CHANGED",
  QUESTIONLIST_CHANGED = "QUESTIONLIST_CHANGED",
  FORCE_LOGIN = "FORCE_LOGIN",
  PREVIEW_ACTIVITY = "PREVIEW_ACTIVITY",
  COURSE_UPDATE_SECTION_SESSION = "COURSE_UPDATE_SECTION_SESSION",
  COURSE_SYNC_UPDATED = "COURSE_SYNC_UPDATED",
  UPDATE_ACTIVITY_SETTINGS = "UPDATE_ACTIVITY_SETTINGS",
  UPDATE_ACTIVITY_SETTINGS_COMPLETED = "UPDATE_ACTIVITY_SETTINGS_COMPLETED",
  UPDATE_ACTIVITY_SETTINGS_FAILED = "UPDATE_ACTIVITY_SETTINGS_FAILED",
  RESET_CONFIRMATION = "RESET_CONFIRMATION",
  INVALID_VIDEO_URL = "INVALID_VIDEO_URL",
}

export const maxTimeLimit = 999999999;

export enum NotificationLevel {
  INFO = "INFO",
  SUCCESS = "SUCCESS",
  WARNING = "WARNING",
  ERROR = "ERROR",
}

export const fileType = {
  imagesComment: 0,
  attFileComment: 1,
  attVideoComment: 2,
  attachFileChat: 3,
  attachImgContent: 4,
  attachVideoContent: 5,
  attachFileContent: 6,
  thumbnailContent: 7,
  assignmentAttach: 9,
  scormFile: 11,
};

export const QUIZ_CONSTANT = {
  TYPE_RANDOM: 0,
  TYPE_FIXED: 1,
};

export const QUIZ_LAYOUT = {
  EveryQuestion: 0,
  EachQuestion: 1,
};

export const VIDEO_SUBTITLE_LANGUAGES = [
  { value: "vi", label: "Vietnamese" },
  { value: "en", label: "English" },
  { value: "jp", label: "Japanese" },
];

export const TAB = {
  TYPING: 0,
  UPLOAD_FILE: 1,
};
export const ID_HELP_TRAINING = process.env.NEXT_PUBLIC_ID_HELP_TRAINING;
export const ID_HELP_FIGHTS = process.env.NEXT_PUBLIC_ID_HELP_FIGHTS;
export const ID_HELP_PAYMENT_INSTRUCTIONS = process.env.NEXT_PUBLIC_ID_HELP_PAYMENT_INSTRUCTIONS;
export const ID_HELP_GENERAL_TRANSACTION = process.env.NEXT_PUBLIC_ID_HELP_GENERAL_TRANSACTION;
export const ID_HELP_SERVICE_USAGE = process.env.NEXT_PUBLIC_ID_HELP_SERVICE_USAGE;
export const ID_HELP_WARRANTY_POLICY = process.env.NEXT_PUBLIC_ID_HELP_WARRANTY_POLICY;
export const ID_HELP_RETURN_POLICY = process.env.NEXT_PUBLIC_ID_HELP_RETURN_POLICY;
export const ID_HELP_PRIVACY_POLICY = process.env.NEXT_PUBLIC_ID_HELP_PRIVACY_POLICY;
